CREATE TABLE IF NOT EXISTS `geo_country` (
  `gc_id` int(11) NOT NULL AUTO_INCREMENT,
  `gc_code2` char(2) NOT NULL DEFAULT '',
  `gc_code3` char(3) NOT NULL DEFAULT '',
  `gc_name` varchar(64) NOT NULL DEFAULT '',
  `gc_nationality` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`gc_id`),
  UNIQUE KEY `code2` (`gc_code2`),
  UNIQUE KEY `code3` (`gc_code3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `geo_country`
--


INSERT INTO `geo_country` (`gc_id`, `gc_code2`, `gc_code3`, `gc_name`, `gc_nationality`) VALUES
(1, 'AW', 'ABW', 'Aruba', NULL),
(2, 'AF', 'AFG', 'Afghanistan', 'Afghan'),
(3, 'AO', 'AGO', 'Angola', 'Angolan'),
(4, 'AI', 'AIA', 'Anguilla', NULL),
(5, 'AX', 'ALA', 'Aland Islands', NULL),
(6, 'AL', 'ALB', 'Albania', 'Albanian'),
(7, 'AD', 'AND', 'Andorra', 'Andorran'),
(8, 'AE', 'ARE', 'United Arab Emirates', 'Emirati'),
(9, 'AR', 'ARG', 'Argentina', 'Argentine'),
(10, 'AM', 'ARM', 'Armenia', 'Armenian'),
(11, 'AS', 'ASM', 'American Samoa', 'Samoan'),
(12, 'AQ', 'ATA', 'Antarctica', NULL),
(13, 'TF', 'ATF', 'French Southern Territories', NULL),
(14, 'AG', 'ATG', 'Antigua and Barbuda', NULL),
(15, 'AU', 'AUS', 'Australia', 'Australian'),
(16, 'AT', 'AUT', 'Austria', 'Austrian'),
(17, 'AZ', 'AZE', 'Azerbaijan', 'Azerbaijani'),
(18, 'BI', 'BDI', 'Burundi', 'Burundian'),
(19, 'BE', 'BEL', 'Belgium', 'Belgian'),
(20, 'BJ', 'BEN', 'Benin', 'Beninese'),
(21, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', NULL),
(22, 'BF', 'BFA', 'Burkina Faso', 'Burkinabe'),
(23, 'BD', 'BGD', 'Bangladesh', 'Bangladeshi'),
(24, 'BG', 'BGR', 'Bulgaria', 'Bulgarian'),
(25, 'BH', 'BHR', 'Bahrain', 'Bahraini'),
(26, 'BS', 'BHS', 'Bahamas', 'Bahamian'),
(27, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Herzegovinian'),
(28, 'BL', 'BLM', 'Saint Barthélemy', NULL),
(29, 'BY', 'BLR', 'Belarus', 'Belarusian'),
(30, 'BZ', 'BLZ', 'Belize', 'Belizean'),
(31, 'BM', 'BMU', 'Bermuda', NULL),
(32, 'BO', 'BOL', 'Bolivia', 'Bolivian'),
(33, 'BR', 'BRA', 'Brazil', 'Brazilian'),
(34, 'BB', 'BRB', 'Barbados', 'Barbadian'),
(35, 'BN', 'BRN', 'Brunei Darussalam', 'Bruneian'),
(36, 'BT', 'BTN', 'Bhutan', 'Bhutanese'),
(37, 'BV', 'BVT', 'Bouvet Island', NULL),
(38, 'BW', 'BWA', 'Botswana', 'Batswana'),
(39, 'CF', 'CAF', 'Central African Republic', 'Central African'),
(40, 'CA', 'CAN', 'Canada', 'Canadian'),
(41, 'CC', 'CCK', 'Cocos (Keeling) Islands', NULL),
(42, 'CH', 'CHE', 'Switzerland', 'Swiss'),
(43, 'CL', 'CHL', 'Chile', 'Chilean'),
(44, 'CN', 'CHN', 'China', 'Chinese'),
(45, 'CI', 'CIV', 'Ivory coast', 'Ivorian'),
(46, 'CM', 'CMR', 'Cameroon', 'Cameroonian'),
(47, 'CD', 'COD', 'Congo', 'Congolese'),
(48, 'CG', 'COG', 'Congo', 'Congolese'),
(49, 'CK', 'COK', 'Cook Islands', NULL),
(50, 'CO', 'COL', 'Colombia', 'Colombian'),
(51, 'KM', 'COM', 'Comoros', 'Comoran'),
(52, 'CV', 'CPV', 'Cabo Verde', 'Cape Verdean'),
(53, 'CR', 'CRI', 'Costa Rica', 'Costa Rican'),
(54, 'CU', 'CUB', 'Cuba', 'Cuban'),
(55, 'CW', 'CUW', 'Curaçao', NULL),
(56, 'CX', 'CXR', 'Christmas Island', NULL),
(57, 'KY', 'CYM', 'Cayman Islands', NULL),
(58, 'CY', 'CYP', 'Cyprus', 'Cypriot'),
(59, 'CZ', 'CZE', 'Czechia', 'Czech'),
(60, 'DE', 'DEU', 'Germany', 'German'),
(61, 'DJ', 'DJI', 'Djibouti', 'Djibouti'),
(62, 'DM', 'DMA', 'Dominica', 'Dominican'),
(63, 'DK', 'DNK', 'Denmark', 'Danish'),
(64, 'DO', 'DOM', 'Dominican Republic', 'Dominican'),
(65, 'DZ', 'DZA', 'Algeria', 'Algerian'),
(66, 'EC', 'ECU', 'Ecuador', 'Ecuadorian'),
(67, 'EG', 'EGY', 'Egypt', 'Egyptian'),
(68, 'ER', 'ERI', 'Eritrea', 'Eritrean'),
(69, 'EH', 'ESH', 'Western Sahara', NULL),
(70, 'ES', 'ESP', 'Spain', 'Spanish'),
(71, 'EE', 'EST', 'Estonia', 'Estonian'),
(72, 'ET', 'ETH', 'Ethiopia', 'Ethiopian'),
(73, 'FI', 'FIN', 'Finland', 'Finnish'),
(74, 'FJ', 'FJI', 'Fiji', 'Fijian'),
(75, 'FK', 'FLK', 'Falkland Islands', NULL),
(76, 'FR', 'FRA', 'France', 'French'),
(77, 'FO', 'FRO', 'Faroe Islands', NULL),
(78, 'FM', 'FSM', 'Micronesia, Federated States of', NULL),
(79, 'GA', 'GAB', 'Gabon', 'Gabonese'),
(80, 'GB', 'GBR', 'United Kingdom', 'English'),
(81, 'GE', 'GEO', 'Georgia', 'Georgian'),
(82, 'GG', 'GGY', 'Guernsey', NULL),
(83, 'GH', 'GHA', 'Ghana', 'Ghanaian'),
(84, 'GI', 'GIB', 'Gibraltar', NULL),
(85, 'GN', 'GIN', 'Guinea', 'Guinean'),
(86, 'GP', 'GLP', 'Guadeloupe', NULL),
(87, 'GM', 'GMB', 'Gambia', 'Gambian'),
(88, 'GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bissauan'),
(89, 'GQ', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinean'),
(90, 'GR', 'GRC', 'Greece', 'Greek'),
(91, 'GD', 'GRD', 'Grenada', 'Grenadian'),
(92, 'GL', 'GRL', 'Greenland', NULL),
(93, 'GT', 'GTM', 'Guatemala', 'Guatemalan'),
(94, 'GF', 'GUF', 'French Guiana', NULL),
(95, 'GU', 'GUM', 'Guam', NULL),
(96, 'GY', 'GUY', 'Guyana', 'Guyanese'),
(97, 'HK', 'HKG', 'Hong Kong', 'Hong Kongese'),
(98, 'HM', 'HMD', 'Heard Island and McDonald Islands', NULL),
(99, 'HN', 'HND', 'Honduras', 'Honduran'),
(100, 'HR', 'HRV', 'Croatia', 'Croatian'),
(101, 'HT', 'HTI', 'Haiti', 'Haitian'),
(102, 'HU', 'HUN', 'Hungary', 'Hungarian'),
(103, 'ID', 'IDN', 'Indonesia', 'Indonesian'),
(104, 'IM', 'IMN', 'Isle of Man', NULL),
(105, 'IN', 'IND', 'India', 'Indian'),
(106, 'IO', 'IOT', 'British Indian Ocean Territory', NULL),
(107, 'IE', 'IRL', 'Ireland', 'Irish'),
(108, 'IR', 'IRN', 'Iran', 'Iranian'),
(109, 'IQ', 'IRQ', 'Iraq', 'Iraqi'),
(110, 'IS', 'ISL', 'Iceland', 'Icelandic'),
(111, 'IL', 'ISR', 'Israel', 'Israeli'),
(112, 'IT', 'ITA', 'Italy', 'Italian'),
(113, 'JM', 'JAM', 'Jamaica', 'Jamaican'),
(114, 'JE', 'JEY', 'Jersey', NULL),
(115, 'JO', 'JOR', 'Jordan', 'Jordanian'),
(116, 'JP', 'JPN', 'Japan', 'Japanese'),
(117, 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstani'),
(118, 'KE', 'KEN', 'Kenya', 'Kenyan'),
(119, 'KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyz'),
(120, 'KH', 'KHM', 'Cambodia', 'Cambodian'),
(121, 'KI', 'KIR', 'Kiribati', 'I-Kiribati'),
(122, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Kittian and Nevisian'),
(123, 'KR', 'KOR', 'Korea, Republic of', 'Korean'),
(124, 'KW', 'KWT', 'Kuwait', 'Kuwaiti'),
(125, 'LA', 'LAO', 'Lao People\'s Democratic Republic', 'Laotian'),
(126, 'LB', 'LBN', 'Lebanon', 'Lebanese'),
(127, 'LR', 'LBR', 'Liberia', 'Liberian'),
(128, 'LY', 'LBY', 'Libya', 'Libyan'),
(129, 'LC', 'LCA', 'Saint Lucia', 'Saint Lucian'),
(130, 'LI', 'LIE', 'Liechtenstein', 'Liechtensteiner'),
(131, 'LK', 'LKA', 'Sri Lanka', 'Sri Lankan'),
(132, 'LS', 'LSO', 'Lesotho', NULL),
(133, 'LT', 'LTU', 'Lithuania', 'Lithuanian'),
(134, 'LU', 'LUX', 'Luxembourg', 'Luxembourger'),
(135, 'LV', 'LVA', 'Latvia', 'Latvian'),
(136, 'MO', 'MAC', 'Macao', NULL),
(137, 'MF', 'MAF', 'Saint Martin (French part)', NULL),
(138, 'MA', 'MAR', 'Morocco', 'Moroccan'),
(139, 'MC', 'MCO', 'Monaco', 'Monacan'),
(140, 'MD', 'MDA', 'Moldova', 'Moldovan'),
(141, 'MG', 'MDG', 'Madagascar', 'Malagasy'),
(142, 'MV', 'MDV', 'Maldives', 'Maldivan'),
(143, 'MX', 'MEX', 'Mexico', 'Mexican'),
(144, 'MH', 'MHL', 'Marshall Islands', 'Marshallese'),
(145, 'MK', 'MKD', 'Macedonia', 'Macedonian'),
(146, 'ML', 'MLI', 'Mali', 'Malian'),
(147, 'MT', 'MLT', 'Malta', 'Maltese'),
(148, 'MM', 'MMR', 'Myanmar', 'Burmese'),
(149, 'ME', 'MNE', 'Montenegro', NULL),
(150, 'MN', 'MNG', 'Mongolia', 'Mongolian'),
(151, 'MP', 'MNP', 'Northern Mariana Islands', NULL),
(152, 'MZ', 'MOZ', 'Mozambique', 'Mozambican'),
(153, 'MR', 'MRT', 'Mauritania', 'Mauritanian'),
(154, 'MS', 'MSR', 'Montserrat', NULL),
(155, 'MQ', 'MTQ', 'Martinique', NULL),
(156, 'MU', 'MUS', 'Mauritius', 'Mauritian'),
(157, 'MW', 'MWI', 'Malawi', 'Malawian'),
(158, 'MY', 'MYS', 'Malaysia', 'Malaysian'),
(159, 'YT', 'MYT', 'Mayotte', NULL),
(160, 'NA', 'NAM', 'Namibia', 'Namibian'),
(161, 'NC', 'NCL', 'New Caledonia', 'New Caledonia'),
(162, 'NE', 'NER', 'Niger', 'Nigerien'),
(163, 'NF', 'NFK', 'Norfolk Island', NULL),
(164, 'NG', 'NGA', 'Nigeria', 'Nigerian'),
(165, 'NI', 'NIC', 'Nicaragua', 'Nicaraguan'),
(166, 'NU', 'NIU', 'Niue', NULL),
(167, 'NL', 'NLD', 'Netherlands', 'Dutch'),
(168, 'NO', 'NOR', 'Norway', 'Norwegian'),
(169, 'NP', 'NPL', 'Nepal', 'Nepalese'),
(170, 'NR', 'NRU', 'Nauru', NULL),
(171, 'NZ', 'NZL', 'New Zealand', 'New Zealand'),
(172, 'OM', 'OMN', 'Oman', 'Omani'),
(173, 'PK', 'PAK', 'Pakistan', 'Pakistani'),
(174, 'PA', 'PAN', 'Panama', 'Panamanian'),
(175, 'PN', 'PCN', 'Pitcairn', NULL),
(176, 'PE', 'PER', 'Peru', 'Peruvian'),
(177, 'PH', 'PHL', 'Philippines', 'Philippine'),
(178, 'PW', 'PLW', 'Palau', 'Palauan'),
(179, 'PG', 'PNG', 'Papua New Guinea', 'Papua New Guinean'),
(180, 'PL', 'POL', 'Poland', 'Polish'),
(181, 'PR', 'PRI', 'Puerto Rico', NULL),
(182, 'KP', 'PRK', 'Korea', 'Korean'),
(183, 'PT', 'PRT', 'Portugal', 'Portuguese'),
(184, 'PY', 'PRY', 'Paraguay', 'Paraguayan'),
(185, 'PS', 'PSE', 'Palestine', NULL),
(186, 'PF', 'PYF', 'French Polynesia', NULL),
(187, 'QA', 'QAT', 'Qatar', 'Qatari'),
(188, 'RE', 'REU', 'Reunion', NULL),
(189, 'RO', 'ROU', 'Romania', 'Romanian'),
(190, 'RU', 'RUS', 'Russia', 'Russian'),
(191, 'RW', 'RWA', 'Rwanda', 'Rwandan'),
(192, 'SA', 'SAU', 'Saudi Arabia', 'Saudi'),
(193, 'SD', 'SDN', 'Sudan', 'Sudanese'),
(194, 'SN', 'SEN', 'Senegal', 'Senegalese'),
(195, 'SG', 'SGP', 'Singapore', 'Singaporean'),
(196, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', NULL),
(197, 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', NULL),
(198, 'SJ', 'SJM', 'Svalbard and Jan Mayen', NULL),
(199, 'SB', 'SLB', 'Solomon Islands', 'Solomon Islander'),
(200, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leonean'),
(201, 'SV', 'SLV', 'El Salvador', 'Salvadorian'),
(202, 'SM', 'SMR', 'San Marino', 'San Marinese'),
(203, 'SO', 'SOM', 'Somalia', 'Somali'),
(204, 'PM', 'SPM', 'Saint Pierre and Miquelon', NULL),
(205, 'RS', 'SRB', 'Serbia', 'Serbian'),
(206, 'SS', 'SSD', 'South Sudan', NULL),
(207, 'ST', 'STP', 'Sao Tome and Principe', NULL),
(208, 'SR', 'SUR', 'Suriname', 'Surinamer'),
(209, 'SK', 'SVK', 'Slovakia', 'Slovak'),
(210, 'SI', 'SVN', 'Slovenia', 'Slovenian'),
(211, 'SE', 'SWE', 'Sweden', 'Swedish'),
(212, 'SZ', 'SWZ', 'Swaziland', 'Swazi'),
(213, 'SX', 'SXM', 'Sint Maarten', NULL),
(214, 'SC', 'SYC', 'Seychelles', 'Seychellois'),
(215, 'SY', 'SYR', 'Syria', 'Syrian'),
(216, 'TC', 'TCA', 'Turks and Caicos Islands', NULL),
(217, 'TD', 'TCD', 'Chad', NULL),
(218, 'TG', 'TGO', 'Togo', 'Togolese'),
(219, 'TH', 'THA', 'Thailand', 'Thai'),
(220, 'TJ', 'TJK', 'Tajikistan', 'Tajik'),
(221, 'TK', 'TKL', 'Tokelau', NULL),
(222, 'TM', 'TKM', 'Turkmenistan', NULL),
(223, 'TL', 'TLS', 'Timor-Leste', NULL),
(224, 'TO', 'TON', 'Tonga', 'Tongan'),
(225, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidadian or Tobagonian'),
(226, 'TN', 'TUN', 'Tunisia', 'Tunisian'),
(227, 'TR', 'TUR', 'Turkey', 'Turkish'),
(228, 'TV', 'TUV', 'Tuvalu', 'Tuvaluan'),
(229, 'TW', 'TWN', 'Taiwan', 'Taiwanese'),
(230, 'TZ', 'TZA', 'Tanzania', 'Tanzanian'),
(231, 'UG', 'UGA', 'Uganda', 'Ugandan'),
(232, 'UA', 'UKR', 'Ukraine', 'Ukrainian'),
(233, 'UM', 'UMI', 'United States Minor Outlying Islands', NULL),
(234, 'UY', 'URY', 'Uruguay', 'Uruguayan'),
(235, 'US', 'USA', 'USA', 'American'),
(236, 'UZ', 'UZB', 'Uzbekistan', 'Uzbekistani'),
(237, 'VA', 'VAT', 'Holy See', NULL),
(238, 'VC', 'VCT', 'Saint Vincent and the Grenadines', NULL),
(239, 'VE', 'VEN', 'Venezuela', 'Venezuelan'),
(240, 'VG', 'VGB', 'Virgin Islands', NULL),
(241, 'VI', 'VIR', 'Virgin Islands, U.S.', NULL),
(242, 'VN', 'VNM', 'Viet Nam', 'Vietnamese'),
(243, 'VU', 'VUT', 'Vanuatu', 'Ni-Vanuatu'),
(244, 'WF', 'WLF', 'Wallis and Futuna', NULL),
(245, 'WS', 'WSM', 'Samoa', NULL),
(246, 'YE', 'YEM', 'Yemen', 'Yemenite'),
(247, 'ZA', 'ZAF', 'South Africa', 'South African'),
(248, 'ZM', 'ZMB', 'Zambia', 'Zambian'),
(249, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwean');